### ISSUE TITLE
Accent color change

### ISSUE THREAD

**Issue by cyanomys** [DarKDinDoN/theme-glass#1]
I love the heck out of this theme but always end up going back to ernie's modern UI (much more complicated overhaul) because I need to change the accent color to match my sheets/game :) A simple accent color picker would be amazing! (like for button selected borders, the little line under the active tab, scrollbars, links.)

**Comment by mech-tools** [comment]
Hi,

Great idea, this is implemented with: [1.6.0](https://github.com/DarKDinDoN/theme-glass/releases/tag/1.6.0)

Couple notes:
- Won't change too much regarding some components such as links, because those are often tied to the system in use (color wise). I try to keep this module as system agnostic as possible.
- Keep in mind that colors should remain unobtrusive. Bright colors might defeat the purpose of this module.


PS: a lot changed for this feature to happen. If you see any issue with this new release, please open an issue on this repository.

**Comment by cyanomys** [comment]
AHHH thank you it looks amazing! 
<img width="1352" alt="image" src="https://github.com/DarKDinDoN/theme-glass/assets/63557988/25ef591e-c003-49dc-8430-b006d99b5770">
